baseURL = "http://localhost:1313/"
paginate = 20
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
metaDataFormat = "toml"
title = "Hugo Hacker News"

[permalinks]
    post = /:year/:month/:day/:slug/

[taxonomies]
    tag = "tags"
    category = "categories"
