language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
install:
  - "pip install -r requirements.txt"
script:
  - "python publish.py"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
