language: python
sudo: required
dist: xenial
python: "3.9"
cache: pip
env:
  - HUGO_VERSION="0.87.0"
before_install:
  - chmod +x ./publish.py
  - curl -sL "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz" -o /tmp/hugo.tar.gz
  - sudo tar -xvf /tmp/hugo.tar.gz -C /usr/local/bin
  - sudo chmod +x /usr/local/bin/hugo
install:
  - "pip install -r requirements.txt"
script: python ./publish.py
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
