language: python
python:
  - "3.6"
cache: pip
env:
  - HUGO_VERSION="0.53"
before_install:
  - chmod +x ./publish.py
  - curl -sL "https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" -o hugo.tar.gz
  - tar -xvf hugo.tar.gz -C /usr/local/bin
  - chmod +x /usr/local/bin/hugo
install:
  - "pip install -r requirements.txt"
script: python ./publish.py
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
