language: python
python:
  - "3.6"
cache: pip
#virtualenv:
#  system_site_packages: true
before_install:
  - chmod +x ./publish.py
install:
  - "pip install -r requirements.txt"
script: python ./publish.py
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
