---
baseURL: "http://davidejones.github.io/hugo-hn/"
languageCode: "en-us"
title: "Hugo Hacker News"
metaDataFormat: "yaml"
permalinks:
  post: /:year/:month/:day/:slug/
theme: "hugo_theme_hn"
publishDir: "docs"
---