---
#baseURL: "http://davidejones.github.io/hugo-hn/"
baseURL: "http://localhost:1313/"
languageCode: "en-us"
title: "Hugo Hacker News"
metaDataFormat: "yaml"
permalinks:
  post: /:year/:month/:day/:slug/
theme: "hugo_theme_hn"
Paginate: 20
taxonomies:
  tag: "tags"
  category: "categories"
menu:
  main:
      - Name: "new"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        URL: "/categories/new/"
      - Name: "comments"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/categories/comments/"
      - Name: "show"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/categories/show/"
      - Name: "ask"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/categories/ask/"
      - Name: "jobs"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/categories/jobs/"
      - Name: "submit"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "https://news.ycombinator.com/submit"
  foot:
      - Name: "Guidelines"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        URL: "/guidelines/"
      - Name: "FAQ"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/faq/"
      - Name: "Support"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/support/"
      - Name: "API"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/api/"
      - Name: "Security"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/security/"
      - Name: "Lists"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/lists/"
      - Name: "Bookmarklet"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/bookmarklet/"
      - Name: "DMCA"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/dmca/"
      - Name: "Apply to YC"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/apply-to-yc/"
      - Name: "Contact"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/contact/"
---
