---
baseURL: "http://localhost:1313/"
languageCode: "en-us"
title: "Hugo Hacker News"
metaDataFormat: "yaml"
permalinks:
  post: /:year/:month/:day/:slug/
theme: "hugo_theme_hn"
Paginate: 20
taxonomies:
  tag: "tags"
  category: "categories"
menu:
  main:
      - Name: "new"
        Weight: 10
        URL: "/"
      - Name: "comments"
        Weight: 20
        URL: "/comments/"
      - Name: "show"
        Weight: 30
        URL: "/categories/show/"
      - Name: "ask"
        Weight: 40
        URL: "/categories/ask/"
      - Name: "jobs"
        Weight: 50
        URL: "/categories/job/"
      - Name: "submit"
        Weight: 60
        URL: "https://news.ycombinator.com/submit"
  foot:
      - Name: "Guidelines"
        Weight: 10
        URL: "/guidelines/"
      - Name: "FAQ"
        Weight: 20
        URL: "/faq/"
      - Name: "Support"
        Weight: 30
        URL: "mailto:hn@ycombinator.com"
      - Name: "API"
        Weight: 40
        URL: "https://github.com/HackerNews/API"
      - Name: "Security"
        Weight: 50
        URL: "/security/"
      - Name: "Lists"
        Weight: 60
        URL: "/lists/"
      - Name: "Bookmarklet"
        Weight: 70
        URL: "https://news.ycombinator.com/bookmarklet.html"
      - Name: "DMCA"
        Weight: 80
        URL: "/dmca/"
      - Name: "Apply to YC"
        Weight: 90
        URL: "http://www.ycombinator.com/apply/"
      - Name: "Contact"
        Weight: 100
        URL: "mailto:hn@ycombinator.com"
---
