[[main]]
  name = "new"
  Weight = 10
  identifier = "new"
  URL = "/"

[[main]]
  name = "comments"
  Weight = 20
  identifier = "comments"
  URL = "/comments/"

[[main]]
  name = "show"
  Weight = 30
  identifier = "show"
  URL = "/categories/show/"

[[main]]
  name = "ask"
  Weight = 40
  identifier = "ask"
  URL = "/categories/ask/"

[[main]]
  name = "jobs"
  Weight = 50
  identifier = "jobs"
  URL = "/categories/jobs/"

[[main]]
  name = "submit"
  Weight = 60
  identifier = "submit"
  URL = "https://news.ycombinator.com/submit"


[[foot]]
  name = "Guidelines"
  Weight = 10
  identifier = "guidelines"
  URL = "/guidelines/"

[[foot]]
  name = "FAQ"
  Weight = 20
  identifier = "faq"
  URL = "/faq/"

[[foot]]
  name = "Support"
  Weight = 30
  identifier = "support"
  URL = "mailto:hn@ycombinator.com"

[[foot]]
  name = "API"
  Weight = 40
  identifier = "api"
  URL = "https://github.com/HackerNews/API"

[[foot]]
  name = "Security"
  Weight = 50
  identifier = "security"
  URL = "/security/"

[[foot]]
  name = "Lists"
  Weight = 60
  identifier = "lists"
  URL = "/lists/"

[[foot]]
  name = "Bookmarklet"
  Weight = 70
  identifier = "bookmarklet"
  URL = "https://news.ycombinator.com/bookmarklet.html"

[[foot]]
  name = "DMCA"
  Weight = 80
  identifier = "DMCA"
  URL = "/dmca/"

[[foot]]
  name = "Apply to YC"
  Weight = 90
  identifier = "apply"
  URL = "http://www.ycombinator.com/apply/"

[[foot]]
  name = "Contact"
  Weight = 100
  identifier = "contact"
  URL = "mailto:hn@ycombinator.com"
